<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <_PropertySheetDisplayName>EmkCommonReleaseX64</_PropertySheetDisplayName>
  </PropertyGroup>
  <PropertyGroup Label="Configuration">
    <EnableASAN>false</EnableASAN>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <InlineFunctionExpansion />
      <FavorSizeOrSpeed />
      <EnableFiberSafeOptimizations />
      <Optimization>MaxSpeed</Optimization>
      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
      <BasicRuntimeChecks>Default</BasicRuntimeChecks>
      <BufferSecurityCheck>false</BufferSecurityCheck>
      <SupportJustMyCode>false</SupportJustMyCode>
      <SDLCheck>false</SDLCheck>
      <WholeProgramOptimization>true</WholeProgramOptimization>
    </ClCompile>
    <Link>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <LinkTimeCodeGeneration>UseLinkTimeCodeGeneration</LinkTimeCodeGeneration>
    </Link>
    <CudaCompile />
    <CudaCompile>
      <Optimization>O2</Optimization>
    </CudaCompile>
    <CudaCompile>
      <Runtime>MD</Runtime>
    </CudaCompile>
    <CudaCompile>
      <RuntimeChecks>Default</RuntimeChecks>
    </CudaCompile>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>