<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <OutDir>$(SolutionDir)..\..\bin\$(Platform)\$(Configuration)\</OutDir>
    <IntDir>$(Platform)\$(Configuration)\</IntDir>
    <LinkIncremental>false</LinkIncremental>
    <CodeAnalysisRuleSet>..\CommonProjectsOptions\VisualStudioStaticAnalysis\NativeRecommendedRules-EMK.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <ExceptionHandling>Async</ExceptionHandling>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <FloatingPointModel>Fast</FloatingPointModel>
      <WarningLevel>Level4</WarningLevel>
      <TreatWarningAsError>true</TreatWarningAsError>
      <TreatSpecificWarningsAsErrors>4596;%(TreatSpecificWarningsAsErrors)</TreatSpecificWarningsAsErrors>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <Optimization>Custom</Optimization>
      <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <FavorSizeOrSpeed />
      <EnableFiberSafeOptimizations />
      <WholeProgramOptimization />
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
      <SDLCheck>false</SDLCheck>
      <BufferSecurityCheck>false</BufferSecurityCheck>
      <ConformanceMode>true</ConformanceMode>
      <BasicRuntimeChecks>Default</BasicRuntimeChecks>
      <RuntimeTypeInfo>true</RuntimeTypeInfo>
      <LanguageStandard_C>stdc17</LanguageStandard_C>
      <SupportJustMyCode>true</SupportJustMyCode>
      <AdditionalOptions>/Zc:__cplusplus /wd4251 %(AdditionalOptions)</AdditionalOptions>
      <EnablePREfast>false</EnablePREfast>
    </ClCompile>
    <Link>
      <OptimizeReferences>true</OptimizeReferences>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
    <CudaCompile>
      <GPUDebugInfo>true</GPUDebugInfo>
      <AdditionalCompilerOptions>
      </AdditionalCompilerOptions>
      <Emulation>No </Emulation>
      <HostDebugInfo>true</HostDebugInfo>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <Defines>GPUSTATICINTERSECTION_EXPORTS;%(Defines)</Defines>
      <Optimization>Od</Optimization>
      <Runtime>MDd</Runtime>
      <RuntimeChecks>RTC1</RuntimeChecks>
      <TypeInfo>true</TypeInfo>
      <Warning>W4</Warning>
    </CudaCompile>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>