<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <_PropertySheetDisplayName>EmkCommonReleaseUnoptimized</_PropertySheetDisplayName>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <FavorSizeOrSpeed />
      <EnableFiberSafeOptimizations />
      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
      <BasicRuntimeChecks>Default</BasicRuntimeChecks>
      <BufferSecurityCheck>false</BufferSecurityCheck>
      <SupportJustMyCode>false</SupportJustMyCode>
      <PreprocessorDefinitions>EMK_RELEASE_UNOPTIMIZED;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <SDLCheck>false</SDLCheck>
      <UseDynamicDebugging>true</UseDynamicDebugging>
      <WholeProgramOptimization>false</WholeProgramOptimization>
      <Optimization>MaxSpeed</Optimization>
      <OmitFramePointers>false</OmitFramePointers>
      <AdditionalOptions>/Zo %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <CudaCompile>
      <Runtime>MD</Runtime>
    </CudaCompile>
    <CudaCompile>
      <RuntimeChecks>Default</RuntimeChecks>
    </CudaCompile>
    <Link>
      <UseDynamicDebugging>true</UseDynamicDebugging>
      <EnableCOMDATFolding>false</EnableCOMDATFolding>
      <LinkTimeCodeGeneration>Default</LinkTimeCodeGeneration>
      <GenerateDebugInformation>DebugFull</GenerateDebugInformation>
    </Link>
    <Lib>
      <UseDynamicDebugging>true</UseDynamicDebugging>
    </Lib>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>